# -*- coding: utf-8 -*-
"""
ACDI Weight Optimization for Agricultural Cold Damage

Purpose
-------
This script extends the existing equal-weight ACDI framework to a weighted ACDI:

    ACDI_w = w1*Z(F1) + w2*Z(F2) + w3*Z(F3) + w4*Z(F4)
    subject to w1 + w2 + w3 + w4 = 1

It generates exactly three manuscript-style figure files:

    Figure 1. Sensitivity analysis of factor weights
        (a) Integrated score sensitivity curves
        (b) Metric-specific sensitivity heatmap

    Figure 2. Response surface analysis
        (a) Integrated performance surface for w3 and w4
        (b) Metric-specific response surface summary

    Figure 3. Pareto optimization and optimized ACDI comparison
        (a) Pareto front
        (b-e) Equal-weight vs optimized-weight ACDI for representative events

Input
-----
CSV files generated by the SMAP download/extraction script:
    event_*_SMAP_L4_SPL4SMGP*_30d_to_3d_4perday_sm_temp_layers.csv

Required columns:
    datetime_kst, event_time_kst,
    sm_surface, sm_rootzone,
    surface_temp, soil_temp_layer1, soil_temp_layer2

Author note
-----------
The factor definitions and event scoring structure follow the user's previous ACDI scripts.
"""

import itertools
import re
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates


# =========================================================
# 1. USER SETTINGS
# =========================================================

SMAP_DIR = Path(
    r"E:\20260426\00 KONKUK\02 Papers\01 SCIE\34th Cold Damage (Weight factor)\python\output_smap_l4_sm_temp_30d_to_3d_4perday"
)

SMAP_PATTERN = "event_*_SMAP_L4_SPL4SMGP*_30d_to_3d_4perday_sm_temp_layers.csv"

OUT_DIR = SMAP_DIR / "acdi_weight_optimization"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Recommended final ACDI configuration from the previous cold-damage paper
# F1: cold intensity temperature source
# F2: rapid cooling temperature source
# F3: vertical thermal gradient
# F4: soil moisture source for cold-dry interaction
SELECTED_CASE = ("surface", "layer1", "L1-SFC", "rootSM")

# Representative events for Figure 3 time-series comparison
REPRESENTATIVE_EVENTS = [2, 3, 5, 7]

# ACDI factor settings
TBASE_C = 5.0
DRY_REF_QUANTILE = 0.75

# Rolling windows
# The data are usually 4 records/day, but the code estimates this automatically.
F1_WINDOW_DAYS = 2   # cold intensity
F2_WINDOW_DAYS = 1   # rapid cooling
F3_WINDOW_DAYS = 1   # vertical gradient
F4_WINDOW_DAYS = 2   # cold-dry interaction

MIN_VALID_RATIO = 0.60

# Evaluation window
EVENT_WINDOW_HOURS = 48

# Duration threshold option:
#   "zero"     : ACDI > 0, consistent with above-mean cold stress
#   "quantile" : ACDI > pre-event quantile, consistent with older ranking code
THRESHOLD_MODE = "zero"
THRESHOLD_Q = 0.90

# Weight search grid
# 0.05 gives 1771 combinations for four factors.
# 0.10 gives 286 combinations and runs much faster.
WEIGHT_STEP = 0.05

# Integrated score weights for the three metrics
# S1: peak dominance, S2: concentration, S3: duration
METRIC_WEIGHTS = {
    "S1_peak_dominance": 1.0,
    "S2_concentration": 1.0,
    "S3_exceedance_duration": 1.0,
}

# Figure output settings
DPI = 300


# =========================================================
# 2. CASE OPTIONS
# =========================================================

F1_OPTIONS = {
    "surface": "surface_temp_C",
    "layer1": "soil_temp_layer1_C",
}

F2_OPTIONS = {
    "surface": "surface_temp_C",
    "layer1": "soil_temp_layer1_C",
}

F3_OPTIONS = {
    "L1-SFC": ("soil_temp_layer1_C", "surface_temp_C"),
    "L2-SFC": ("soil_temp_layer2_C", "surface_temp_C"),
    "L2-L1": ("soil_temp_layer2_C", "soil_temp_layer1_C"),
}

F4_OPTIONS = {
    "surfSM": "sm_surface",
    "rootSM": "sm_rootzone",
}

FACTOR_LABELS = {
    "w1": "F1: cold intensity",
    "w2": "F2: rapid cooling",
    "w3": "F3: thermal imbalance",
    "w4": "F4: cold-dry interaction",
}

METRIC_LABELS = {
    "S1_peak_dominance": "Peak dominance",
    "S2_concentration": "Concentration",
    "S3_exceedance_duration": "Exceedance duration",
    "Integrated_score": "Integrated score",
}


# =========================================================
# 3. UTILITIES
# =========================================================

def infer_event_id_from_filename(path: Path) -> int:
    m = re.search(r"event_(\d+)", path.name)
    if not m:
        raise ValueError(f"Cannot parse event id from file name: {path.name}")
    return int(m.group(1))


def to_kst_naive(ts) -> pd.Timestamp:
    ts = pd.Timestamp(ts)
    if ts.tzinfo is not None:
        ts = ts.tz_convert("Asia/Seoul").tz_localize(None)
    return ts


def zscore_series(s: pd.Series) -> pd.Series:
    s = pd.to_numeric(s, errors="coerce")
    mu = s.mean(skipna=True)
    sd = s.std(skipna=True, ddof=0)

    if pd.isna(sd) or sd == 0:
        return pd.Series(np.zeros(len(s)), index=s.index, dtype=float)

    return (s - mu) / sd


def estimate_steps_per_day(df: pd.DataFrame) -> int:
    dt = df["date_plot"].sort_values().diff().dropna()
    if len(dt) == 0:
        return 4

    median_hours = dt.dt.total_seconds().median() / 3600.0
    if median_hours <= 0 or pd.isna(median_hours):
        return 4

    return max(1, int(round(24.0 / median_hours)))


def days_to_steps(df: pd.DataFrame, days: int):
    steps_per_day = estimate_steps_per_day(df)
    window_steps = max(1, int(days * steps_per_day))
    min_periods = max(1, int(np.ceil(window_steps * MIN_VALID_RATIO)))
    return window_steps, min_periods


def safe_nanmax(x):
    x = pd.Series(x).dropna()
    return np.nan if len(x) == 0 else float(np.nanmax(x))


def safe_nanmean(x):
    x = pd.Series(x).dropna()
    return np.nan if len(x) == 0 else float(np.nanmean(x))


def normalize_0_1(s: pd.Series) -> pd.Series:
    s = pd.to_numeric(s, errors="coerce")
    mn, mx = s.min(skipna=True), s.max(skipna=True)

    if pd.isna(mn) or pd.isna(mx) or mx == mn:
        return pd.Series(np.zeros(len(s)), index=s.index, dtype=float)

    return (s - mn) / (mx - mn)


# =========================================================
# 4. LOAD SMAP EVENT DATA
# =========================================================

def load_smap_event_csv(path: Path):
    df = pd.read_csv(path, encoding="utf-8-sig")

    required = {
        "datetime_kst",
        "event_time_kst",
        "sm_surface",
        "sm_rootzone",
        "surface_temp",
        "soil_temp_layer1",
        "soil_temp_layer2",
    }
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{path.name} is missing required columns: {sorted(missing)}")

    df["date"] = pd.to_datetime(df["datetime_kst"], errors="coerce")
    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    df["date_plot"] = df["date"].apply(to_kst_naive)

    event_time = pd.to_datetime(df["event_time_kst"].iloc[0], errors="coerce")
    if pd.isna(event_time):
        raise ValueError(f"Failed to parse event_time_kst in {path.name}")
    event_time = to_kst_naive(event_time)

    temp_cols_k = [
        "surface_temp",
        "soil_temp_layer1",
        "soil_temp_layer2",
        "soil_temp_layer3",
        "soil_temp_layer4",
        "soil_temp_layer5",
        "soil_temp_layer6",
    ]

    for c in temp_cols_k:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
            df[c + "_C"] = df[c] - 273.15

    for c in ["sm_surface", "sm_rootzone"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    if "event_id" in df.columns:
        event_id = int(df["event_id"].iloc[0])
    else:
        event_id = infer_event_id_from_filename(path)

    return event_id, event_time, df


# =========================================================
# 5. FACTOR FUNCTIONS
# =========================================================

def compute_cold_intensity(df: pd.DataFrame, temp_col: str) -> pd.Series:
    steps, min_periods = days_to_steps(df, F1_WINDOW_DAYS)
    cold_deficit = (TBASE_C - df[temp_col]).clip(lower=0)
    return cold_deficit.rolling(steps, min_periods=min_periods).mean()


def compute_rapid_cooling(df: pd.DataFrame, temp_col: str) -> pd.Series:
    steps, min_periods = days_to_steps(df, F2_WINDOW_DAYS)
    dtemp = df[temp_col].diff()
    shock = (-dtemp).clip(lower=0)
    return shock.rolling(steps, min_periods=min_periods).mean()


def compute_vertical_gradient(df: pd.DataFrame, upper_col: str, lower_col: str) -> pd.Series:
    steps, min_periods = days_to_steps(df, F3_WINDOW_DAYS)
    gradient = (df[upper_col] - df[lower_col]).clip(lower=0)
    return gradient.rolling(steps, min_periods=min_periods).mean()


def compute_dryness(df: pd.DataFrame, sm_col: str) -> pd.Series:
    steps, min_periods = days_to_steps(df, F4_WINDOW_DAYS)
    sm_roll = df[sm_col].rolling(steps, min_periods=min_periods).mean()
    sm_ref = sm_roll.quantile(DRY_REF_QUANTILE)
    return (sm_ref - sm_roll).clip(lower=0)


def compute_factor_table(
    df: pd.DataFrame,
    f1_key: str,
    f2_key: str,
    f3_key: str,
    f4_key: str,
) -> pd.DataFrame:
    f1_col = F1_OPTIONS[f1_key]
    f2_col = F2_OPTIONS[f2_key]
    f3_upper_col, f3_lower_col = F3_OPTIONS[f3_key]
    f4_sm_col = F4_OPTIONS[f4_key]

    F1 = compute_cold_intensity(df, f1_col)
    F2 = compute_rapid_cooling(df, f2_col)
    F3 = compute_vertical_gradient(df, f3_upper_col, f3_lower_col)

    dryness = compute_dryness(df, f4_sm_col)
    F4_raw = zscore_series(F1) * zscore_series(dryness)

    out = pd.DataFrame({
        "date_plot": df["date_plot"],
        "Z_F1": zscore_series(F1),
        "Z_F2": zscore_series(F2),
        "Z_F3": zscore_series(F3),
        "Z_F4": zscore_series(F4_raw),
    })

    return out


def compute_weighted_acdi(factor_df: pd.DataFrame, weights: dict) -> pd.Series:
    return (
        weights["w1"] * factor_df["Z_F1"]
        + weights["w2"] * factor_df["Z_F2"]
        + weights["w3"] * factor_df["Z_F3"]
        + weights["w4"] * factor_df["Z_F4"]
    )


# =========================================================
# 6. METRICS
# =========================================================

def compute_scores(acdi: pd.Series, dates: pd.Series, event_time: pd.Timestamp):
    event_start = event_time - pd.Timedelta(hours=EVENT_WINDOW_HOURS)

    dates = pd.Series(dates).apply(to_kst_naive)
    event_time = to_kst_naive(event_time)

    mask_event = (dates >= event_start) & (dates <= event_time)
    mask_early = dates < event_start
    mask_pre = dates < event_time

    event_vals = pd.Series(acdi[mask_event]).dropna()
    early_vals = pd.Series(acdi[mask_early]).dropna()
    pre_vals = pd.Series(acdi[mask_pre]).dropna()

    if len(event_vals) == 0 or len(pre_vals) == 0:
        return np.nan, np.nan, np.nan

    sigma = float(np.nanstd(pre_vals))
    if pd.isna(sigma) or sigma == 0:
        sigma = 1e-6

    # S1: peak dominance
    p_event = safe_nanmax(event_vals)
    p_early = safe_nanmax(early_vals)
    S1 = (p_event - p_early) / sigma

    # S2: concentration
    m_event = safe_nanmean(event_vals)
    m_early = safe_nanmean(early_vals)
    S2 = (m_event - m_early) / sigma

    # S3: exceedance duration
    if THRESHOLD_MODE.lower() == "zero":
        threshold = 0.0
    elif THRESHOLD_MODE.lower() == "quantile":
        threshold = float(np.nanquantile(pre_vals, THRESHOLD_Q))
    else:
        raise ValueError("THRESHOLD_MODE must be either 'zero' or 'quantile'.")

    # Unit: number of data points within the 48-h event window.
    # With 4 observations/day, this is approximately 6-hour units.
    S3 = float(np.sum(event_vals > threshold))

    return S1, S2, S3


# =========================================================
# 7. WEIGHT GRID AND OPTIMIZATION
# =========================================================

def generate_simplex_weights(step: float) -> pd.DataFrame:
    values = np.round(np.arange(0, 1 + step / 2, step), 10)

    rows = []
    for w1 in values:
        for w2 in values:
            for w3 in values:
                w4 = 1.0 - w1 - w2 - w3
                if w4 < -1e-9:
                    continue
                if w4 > 1 + 1e-9:
                    continue
                w4 = round(w4, 10)
                if abs((w1 + w2 + w3 + w4) - 1.0) <= 1e-9:
                    rows.append({"w1": w1, "w2": w2, "w3": w3, "w4": w4})

    return pd.DataFrame(rows)


def build_all_event_factor_tables(files):
    f1_key, f2_key, f3_key, f4_key = SELECTED_CASE

    event_tables = []
    for path in files:
        event_id, event_time, df = load_smap_event_csv(path)
        factor_df = compute_factor_table(df, f1_key, f2_key, f3_key, f4_key)

        event_tables.append({
            "event_id": event_id,
            "event_time": event_time,
            "dates": df["date_plot"].copy(),
            "factor_df": factor_df,
        })

    return event_tables


def evaluate_weight_grid(event_tables, weight_df):
    rows = []

    for _, wr in weight_df.iterrows():
        weights = {
            "w1": float(wr["w1"]),
            "w2": float(wr["w2"]),
            "w3": float(wr["w3"]),
            "w4": float(wr["w4"]),
        }

        for ev in event_tables:
            acdi = compute_weighted_acdi(ev["factor_df"], weights)
            S1, S2, S3 = compute_scores(acdi, ev["dates"], ev["event_time"])

            rows.append({
                "event": ev["event_id"],
                **weights,
                "S1_peak_dominance": S1,
                "S2_concentration": S2,
                "S3_exceedance_duration": S3,
            })

    return pd.DataFrame(rows)


def add_integrated_score(mean_df: pd.DataFrame) -> pd.DataFrame:
    out = mean_df.copy()

    metric_cols = list(METRIC_WEIGHTS.keys())
    for col in metric_cols:
        out[col + "_norm"] = normalize_0_1(out[col])

    total_weight = sum(METRIC_WEIGHTS.values())
    out["Integrated_score"] = 0.0

    for col, w in METRIC_WEIGHTS.items():
        out["Integrated_score"] += (w / total_weight) * out[col + "_norm"]

    return out


def summarize_weight_results(event_metric_df: pd.DataFrame):
    metric_cols = [
        "S1_peak_dominance",
        "S2_concentration",
        "S3_exceedance_duration",
    ]

    mean_df = (
        event_metric_df
        .groupby(["w1", "w2", "w3", "w4"], as_index=False)[metric_cols]
        .mean()
    )

    mean_df = add_integrated_score(mean_df)
    mean_df = mean_df.sort_values("Integrated_score", ascending=False).reset_index(drop=True)

    return mean_df


def find_pareto_front(df: pd.DataFrame, objective_cols):
    values = df[objective_cols].to_numpy(dtype=float)

    # Maximize all objectives.
    is_pareto = np.ones(values.shape[0], dtype=bool)

    for i, v in enumerate(values):
        if not is_pareto[i]:
            continue

        dominates_i = np.all(values >= v, axis=1) & np.any(values > v, axis=1)
        if np.any(dominates_i):
            is_pareto[i] = False

    return df.loc[is_pareto].copy().sort_values("Integrated_score", ascending=False)


# =========================================================
# 8. SENSITIVITY ANALYSIS
# =========================================================

def build_sensitivity_table(event_tables):
    rows = []
    values = np.round(np.arange(0, 1.0 + WEIGHT_STEP / 2, WEIGHT_STEP), 10)

    for target in ["w1", "w2", "w3", "w4"]:
        others = [w for w in ["w1", "w2", "w3", "w4"] if w != target]

        for target_value in values:
            remaining = 1.0 - target_value
            weights = {target: float(target_value)}
            for o in others:
                weights[o] = float(remaining / 3.0)

            event_rows = []
            for ev in event_tables:
                acdi = compute_weighted_acdi(ev["factor_df"], weights)
                S1, S2, S3 = compute_scores(acdi, ev["dates"], ev["event_time"])
                event_rows.append({
                    "S1_peak_dominance": S1,
                    "S2_concentration": S2,
                    "S3_exceedance_duration": S3,
                })

            tmp = pd.DataFrame(event_rows)
            mean_values = tmp.mean(numeric_only=True).to_dict()

            rows.append({
                "target_factor": target,
                "target_weight": target_value,
                **weights,
                **mean_values,
            })

    sens_df = pd.DataFrame(rows)

    # Normalize within the sensitivity table so that integrated score is comparable.
    sens_df = add_integrated_score(sens_df)

    return sens_df


# =========================================================
# 9. RESPONSE SURFACE
# =========================================================

def build_response_surface(mean_df: pd.DataFrame):
    """
    Summarize performance over w3 and w4.
    If several w1-w2 splits exist for the same w3-w4 pair,
    keep the maximum integrated score.
    """
    idx = (
        mean_df
        .sort_values("Integrated_score", ascending=False)
        .groupby(["w3", "w4"], as_index=False)
        .head(1)
        .reset_index(drop=True)
    )
    return idx


def pivot_surface(surface_df: pd.DataFrame, value_col: str):
    mat = surface_df.pivot_table(
        index="w4",
        columns="w3",
        values=value_col,
        aggfunc="max",
    )
    mat = mat.sort_index(ascending=True)
    mat = mat.reindex(sorted(mat.columns), axis=1)
    return mat


# =========================================================
# 10. PLOTTING HELPERS
# =========================================================

def add_panel_label(ax, label):
    ax.text(
        0.01, 0.98, label,
        transform=ax.transAxes,
        ha="left", va="top",
        fontsize=12,
        fontweight="bold",
        bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.8, edgecolor="none"),
    )


def format_time_axis(ax):
    locator = mdates.AutoDateLocator(minticks=4, maxticks=7)
    formatter = mdates.DateFormatter("%Y-%m-%d")
    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(formatter)
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")


def plot_heatmap_matrix(ax, mat, title, cbar_label):
    im = ax.imshow(mat.values, origin="lower", aspect="auto")

    ax.set_title(title)
    ax.set_xlabel("Weight of F3")
    ax.set_ylabel("Weight of F4")

    ax.set_xticks(np.arange(len(mat.columns)))
    ax.set_xticklabels([f"{v:.2f}" for v in mat.columns], rotation=45, ha="right", fontsize=8)

    ax.set_yticks(np.arange(len(mat.index)))
    ax.set_yticklabels([f"{v:.2f}" for v in mat.index], fontsize=8)

    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label(cbar_label)

    return im


# =========================================================
# 11. FIGURE 1: SENSITIVITY
# =========================================================

def plot_figure_1_sensitivity(sens_df: pd.DataFrame, out_dir: Path):
    fig, axes = plt.subplots(1, 2, figsize=(15, 6), constrained_layout=True)

    ax = axes[0]
    for factor in ["w1", "w2", "w3", "w4"]:
        sub = sens_df[sens_df["target_factor"] == factor].sort_values("target_weight")
        ax.plot(
            sub["target_weight"],
            sub["Integrated_score"],
            marker="o",
            linewidth=1.8,
            label=FACTOR_LABELS[factor],
        )

    ax.set_xlabel("Assigned weight to target factor")
    ax.set_ylabel("Integrated performance score")
    ax.set_title("One-factor-at-a-time sensitivity")
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=9)
    add_panel_label(ax, "(a)")

    # Metric-specific heatmap:
    # For each factor, compute the performance range caused by varying that factor.
    heat_rows = []
    for factor in ["w1", "w2", "w3", "w4"]:
        sub = sens_df[sens_df["target_factor"] == factor]
        row = {"Factor": FACTOR_LABELS[factor]}
        for metric in ["S1_peak_dominance", "S2_concentration", "S3_exceedance_duration", "Integrated_score"]:
            row[metric] = sub[metric].max() - sub[metric].min()
        heat_rows.append(row)

    heat_df = pd.DataFrame(heat_rows).set_index("Factor")
    heat_df_norm = heat_df.copy()
    for c in heat_df_norm.columns:
        heat_df_norm[c] = normalize_0_1(heat_df_norm[c])

    ax = axes[1]
    im = ax.imshow(heat_df_norm.values, aspect="auto")
    ax.set_title("Relative sensitivity by metric")
    ax.set_xticks(np.arange(len(heat_df_norm.columns)))
    ax.set_xticklabels([METRIC_LABELS.get(c, c) for c in heat_df_norm.columns], rotation=35, ha="right")
    ax.set_yticks(np.arange(len(heat_df_norm.index)))
    ax.set_yticklabels(heat_df_norm.index)

    for i in range(heat_df_norm.shape[0]):
        for j in range(heat_df_norm.shape[1]):
            ax.text(j, i, f"{heat_df_norm.iloc[i, j]:.2f}", ha="center", va="center", fontsize=9)

    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label("Normalized sensitivity range")
    add_panel_label(ax, "(b)")

    out_png = out_dir / "Figure_1_sensitivity_analysis.png"
    fig.savefig(out_png, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    print(f"[OK] saved: {out_png}")


# =========================================================
# 12. FIGURE 2: RESPONSE SURFACE
# =========================================================

def plot_figure_2_response_surface(surface_df: pd.DataFrame, best_row: pd.Series, out_dir: Path):
    fig, axes = plt.subplots(1, 2, figsize=(15, 6), constrained_layout=True)

    # (a) Integrated score surface
    mat_score = pivot_surface(surface_df, "Integrated_score")
    ax = axes[0]
    plot_heatmap_matrix(ax, mat_score, "Response surface of integrated performance", "Integrated score")

    # Mark optimum
    w3_values = list(mat_score.columns)
    w4_values = list(mat_score.index)
    if best_row["w3"] in w3_values and best_row["w4"] in w4_values:
        x = w3_values.index(best_row["w3"])
        y = w4_values.index(best_row["w4"])
        ax.scatter(x, y, s=120, marker="*", edgecolor="black", linewidth=1.0)
        ax.text(x, y, "  Opt.", va="center", fontsize=9)

    add_panel_label(ax, "(a)")

    # (b) Response surface of the best metric among three metrics
    # Here we show normalized mean of the three individual metric surfaces
    tmp = surface_df.copy()
    for m in ["S1_peak_dominance", "S2_concentration", "S3_exceedance_duration"]:
        tmp[m + "_surface_norm"] = normalize_0_1(tmp[m])

    tmp["Metric_balance"] = (
        tmp["S1_peak_dominance_surface_norm"]
        + tmp["S2_concentration_surface_norm"]
        + tmp["S3_exceedance_duration_surface_norm"]
    ) / 3.0

    mat_balance = pivot_surface(tmp, "Metric_balance")
    ax = axes[1]
    plot_heatmap_matrix(ax, mat_balance, "Balanced metric response surface", "Balanced metric score")

    if best_row["w3"] in list(mat_balance.columns) and best_row["w4"] in list(mat_balance.index):
        x = list(mat_balance.columns).index(best_row["w3"])
        y = list(mat_balance.index).index(best_row["w4"])
        ax.scatter(x, y, s=120, marker="*", edgecolor="black", linewidth=1.0)
        ax.text(x, y, "  Opt.", va="center", fontsize=9)

    add_panel_label(ax, "(b)")

    out_png = out_dir / "Figure_2_response_surface.png"
    fig.savefig(out_png, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    print(f"[OK] saved: {out_png}")


# =========================================================
# 13. FIGURE 3: PARETO + TIME SERIES
# =========================================================

def plot_figure_3_pareto_and_timeseries(
    mean_df: pd.DataFrame,
    pareto_df: pd.DataFrame,
    event_tables,
    best_row: pd.Series,
    out_dir: Path,
):
    fig = plt.figure(figsize=(16, 12), constrained_layout=True)
    gs = fig.add_gridspec(3, 2)

    # -------------------------
    # (a) Pareto front
    # -------------------------
    ax = fig.add_subplot(gs[0, :])

    ax.scatter(
        mean_df["S1_peak_dominance"],
        mean_df["S2_concentration"],
        s=24,
        alpha=0.35,
        label="All weight combinations",
    )

    ax.scatter(
        pareto_df["S1_peak_dominance"],
        pareto_df["S2_concentration"],
        s=48,
        alpha=0.9,
        label="Pareto-optimal combinations",
    )

    ax.scatter(
        best_row["S1_peak_dominance"],
        best_row["S2_concentration"],
        s=180,
        marker="*",
        edgecolor="black",
        linewidth=1.0,
        label="Selected optimum",
    )

    ax.set_xlabel("Peak dominance")
    ax.set_ylabel("Concentration")
    ax.set_title("Pareto-based multi-objective optimization")
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=9)
    add_panel_label(ax, "(a)")

    # -------------------------
    # (b-e) equal vs optimized ACDI
    # -------------------------
    equal_weights = {"w1": 0.25, "w2": 0.25, "w3": 0.25, "w4": 0.25}
    opt_weights = {
        "w1": float(best_row["w1"]),
        "w2": float(best_row["w2"]),
        "w3": float(best_row["w3"]),
        "w4": float(best_row["w4"]),
    }

    panel_labels = ["(b)", "(c)", "(d)", "(e)"]
    axes_ts = [
        fig.add_subplot(gs[1, 0]),
        fig.add_subplot(gs[1, 1]),
        fig.add_subplot(gs[2, 0]),
        fig.add_subplot(gs[2, 1]),
    ]

    event_dict = {ev["event_id"]: ev for ev in event_tables}

    for ax, eid, lab in zip(axes_ts, REPRESENTATIVE_EVENTS, panel_labels):
        if eid not in event_dict:
            ax.axis("off")
            ax.text(0.5, 0.5, f"Event {eid} not found", ha="center", va="center")
            continue

        ev = event_dict[eid]
        dates = ev["factor_df"]["date_plot"]
        acdi_equal = compute_weighted_acdi(ev["factor_df"], equal_weights)
        acdi_opt = compute_weighted_acdi(ev["factor_df"], opt_weights)

        ax.plot(dates, acdi_equal, linewidth=1.4, linestyle="--", label="Equal-weight ACDI")
        ax.plot(dates, acdi_opt, linewidth=1.8, label="Optimized-weight ACDI")
        ax.axvline(ev["event_time"], linestyle="--", linewidth=1.4, label="Event time")
        ax.axhline(0.0, linestyle=":", linewidth=1.0)

        # focus on -10 d to +3 d for visibility
        start = ev["event_time"] - pd.Timedelta(days=10)
        end = ev["event_time"] + pd.Timedelta(days=3)
        ax.set_xlim(start, end)

        ax.set_title(f"Event {eid}")
        ax.set_ylabel("ACDI")
        ax.grid(True, alpha=0.3)
        format_time_axis(ax)
        add_panel_label(ax, lab)

    axes_ts[0].legend(fontsize=8, loc="upper left")

    out_png = out_dir / "Figure_3_pareto_and_optimized_timeseries.png"
    fig.savefig(out_png, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    print(f"[OK] saved: {out_png}")


# =========================================================
# 14. MAIN
# =========================================================

def main():
    files = sorted(SMAP_DIR.glob(SMAP_PATTERN))
    if not files:
        raise FileNotFoundError(
            "SMAP event CSV files were not found.\n"
            f"SMAP_DIR = {SMAP_DIR}\n"
            f"SMAP_PATTERN = {SMAP_PATTERN}"
        )

    print(f"[INFO] Found {len(files)} SMAP event files")
    print(f"[INFO] Selected ACDI case: F1={SELECTED_CASE[0]}, F2={SELECTED_CASE[1]}, F3={SELECTED_CASE[2]}, F4={SELECTED_CASE[3]}")
    print(f"[INFO] Weight step: {WEIGHT_STEP}")

    # -----------------------------------------------------
    # Build factor tables once, then reuse them for all weights
    # -----------------------------------------------------
    event_tables = build_all_event_factor_tables(files)
    print(f"[INFO] Built factor tables for {len(event_tables)} events")

    # -----------------------------------------------------
    # Full simplex weight search
    # -----------------------------------------------------
    weight_df = generate_simplex_weights(WEIGHT_STEP)
    weight_df.to_csv(OUT_DIR / "weight_grid.csv", index=False, encoding="utf-8-sig")
    print(f"[INFO] Weight combinations: {len(weight_df)}")

    event_metric_df = evaluate_weight_grid(event_tables, weight_df)
    event_metric_df.to_csv(
        OUT_DIR / "weight_grid_event_metrics.csv",
        index=False,
        encoding="utf-8-sig",
    )

    mean_df = summarize_weight_results(event_metric_df)
    mean_df.to_csv(
        OUT_DIR / "weight_grid_mean_metrics.csv",
        index=False,
        encoding="utf-8-sig",
    )

    best_row = mean_df.iloc[0]
    pd.DataFrame([best_row]).to_csv(
        OUT_DIR / "selected_optimized_weight.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print("[RESULT] Selected optimized weights")
    print(f"  w1 = {best_row['w1']:.2f}  ({FACTOR_LABELS['w1']})")
    print(f"  w2 = {best_row['w2']:.2f}  ({FACTOR_LABELS['w2']})")
    print(f"  w3 = {best_row['w3']:.2f}  ({FACTOR_LABELS['w3']})")
    print(f"  w4 = {best_row['w4']:.2f}  ({FACTOR_LABELS['w4']})")
    print(f"  Integrated score = {best_row['Integrated_score']:.4f}")

    # -----------------------------------------------------
    # Pareto front
    # -----------------------------------------------------
    objective_cols = [
        "S1_peak_dominance",
        "S2_concentration",
        "S3_exceedance_duration",
    ]
    pareto_df = find_pareto_front(mean_df, objective_cols)
    pareto_df.to_csv(OUT_DIR / "pareto_optimal_weights.csv", index=False, encoding="utf-8-sig")
    print(f"[INFO] Pareto solutions: {len(pareto_df)}")

    # -----------------------------------------------------
    # Sensitivity table
    # -----------------------------------------------------
    sens_df = build_sensitivity_table(event_tables)
    sens_df.to_csv(OUT_DIR / "sensitivity_analysis_results.csv", index=False, encoding="utf-8-sig")

    # -----------------------------------------------------
    # Response surface
    # -----------------------------------------------------
    surface_df = build_response_surface(mean_df)
    surface_df.to_csv(OUT_DIR / "response_surface_w3_w4.csv", index=False, encoding="utf-8-sig")

    # -----------------------------------------------------
    # Figures: exactly three figure files
    # -----------------------------------------------------
    plot_figure_1_sensitivity(sens_df, OUT_DIR)
    plot_figure_2_response_surface(surface_df, best_row, OUT_DIR)
    plot_figure_3_pareto_and_timeseries(mean_df, pareto_df, event_tables, best_row, OUT_DIR)

    print("\n[DONE] ACDI weight optimization completed.")
    print(f"[DONE] Results and figures saved in:\n  {OUT_DIR}")


if __name__ == "__main__":
    main()
